// build.mjs — 生成内嵌 UI -> bun build --compile 打包单文件绿色 exe
import { readFileSync, writeFileSync, mkdirSync, statSync } from 'node:fs';
import path from 'node:path';
import { execSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const ROOT = path.dirname(fileURLToPath(import.meta.url));
const UI = path.join(ROOT, 'ui');

// 1. 生成 src/ui-files.js：把 ui 三件套以字符串内嵌，供 server.js 静态服务
const files = ['index.html', 'style.css', 'app.js'];
const obj = {};
for (const f of files) obj[f] = readFileSync(path.join(UI, f), 'utf8');
const out = `// AUTO-GENERATED by build.mjs — do not edit\nconst UI_FILES = ${JSON.stringify(obj)};\nexport { UI_FILES };\n`;
writeFileSync(path.join(ROOT, 'src', 'ui-files.js'), out, 'utf8');
console.log('embedded ui-files.js');

// 2. bun build --compile 打包单文件 exe
const bun = process.env.BUN || 'C:\\Users\\xubin\\.bun\\bin\\bun.exe';
mkdirSync(path.join(ROOT, 'dist'), { recursive: true });
const outExe = path.join(ROOT, 'dist', 'SweepWise.exe');
const cmd = `"${bun}" build --compile --target=bun-windows-x64 --minify --outfile "${outExe}" "${path.join(ROOT, 'server.js')}"`;
console.log('>>', cmd);
execSync(cmd, { stdio: 'inherit', cwd: ROOT });
const st = statSync(outExe);
console.log(`OK SweepWise.exe ${(st.size / 1024 / 1024).toFixed(1)} MB`);